# Generated by Django 4.2.21 on 2025-08-11 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_actor_film_duration_minutes_series_film_actors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='film',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='film',
            name='duration_minutes',
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
    ]
