# Generated by Django 4.2.21 on 2025-08-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
    ]
